name: Build it and test it
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Grand Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Build and Test
        id: sbt
        uses: lokkju/github-action-sbt@master
        with:
          commands: test
