name: Build it and test it
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches-ignore:
      - "feature/*"  # don't run build/test against a feature branch -- no SLA there
  pull_request:
    branches-ignore:
      - "feature/*"

jobs:
  build:
    name: Grand Build
    runs-on: ubuntu-latest

    steps:
      - name: Echo the greeting's time
        run: echo 'Event-> ${github.event}}'

      - name: Echo the greeting's time
        run: echo 'base_ref-> ${{github.base_ref}}'

      - name: Echo the greeting's time
        run: echo 'head_ref-> ${{github.head_ref}}'

      - name: Echo the greeting's time
        run: echo 'ref-> ${{github.ref}}'
